SEVERITY_SCORES = {
    "low": 2,
    "medium": 5,
    "high": 7,
    "critical": 9
}


AGGRESSIVE_TERMS = [
    "without notice",
    "sole discretion",
    "at any time",
    "without consent",
    "automatically",
    "non-refundable",
    "perpetual",
    "irrevocable",
    "third parties",

    "without liability",
    "without compensation",
    "without prior approval",
    "without user permission",
    "without warning",
    "without restriction",
    "without limitation",
    "without recourse",
    "without refund",
    "without obligation",

    "binding arbitration",
    "mandatory arbitration",
    "waive all rights",
    "waiver of rights",
    "waive the right",
    "no legal responsibility",
    "hold harmless",
    "indemnify the company",
    "release from liability",
    "not liable for damages",

    "exclusive jurisdiction",
    "final and binding",
    "notwithstanding anything",
    "absolute discretion",
    "unlimited liability",
    "unlimited rights",
    "worldwide license",
    "royalty-free",
    "fully transferable",
    "sub-licensable",

    "permanent suspension",
    "terminate immediately",
    "account may be terminated",
    "access may be revoked",
    "services may be discontinued",
    "rights may be revoked",
    "benefits may be withdrawn",
    "subject to removal",
    "subject to termination",

    "collect and store",
    "share with advertisers",
    "sell your data",
    "disclose personal information",
    "transfer your information",
    "monitor your activity",
    "track your location",
    "record communications",
    "retain data indefinitely",

    "class action waiver",
    "no class actions",
    "individual claims only",
    "disputes shall be resolved",
    "users must arbitrate",
    "court proceedings waived",
    "no right to sue",
    "legal remedies limited",

    "fees may increase",
    "charges may apply",
    "pricing subject to change",
    "additional costs may apply",
    "recurring billing",
    "automatic renewal",
    "payment authorization",
    "auto-debit authorization",

    "at the company's discretion",
    "as determined by us",
    "we reserve the right",
    "may modify at any time",
    "may change without notice",
    "may remove content",
    "may deny access",
    "may suspend accounts",
    "may delete data",

    "no warranty",
    "as is basis",
    "as available basis",
    "no guarantees",
    "service not guaranteed",
    "use at your own risk",
    "assume all risk",
    "disclaims all liability",

    "permanent license",
    "exclusive rights granted",
    "grant us all rights",
    "assign all rights",
    "ownership transfers to us",
    "content becomes our property",

    "survive termination",
    "in perpetuity",
    "forever irrevocable",
    "cannot be cancelled",
    "cannot be revoked",
    "non-cancellable",
    "legally binding forever"
    "third parties"
]


SEVERITY_COLORS = {
    "low": "green",
    "medium": "orange",
    "high": "orangered",
    "critical": "red"
}